POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@doe.com"
}

###
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "0548f534-5993-4287-bf02-49a95eba630a"
}

###
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "11030f5b-aa5f-44af-b193-62be6bde8d93",
  "account_id_to": "bcd8c693-68b2-4686-941c-3ddb43d4f2bf",
  "amount": 100
}